name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build: # This creates a docker container running linux on it.
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: create static deployment file
        run: |
          mkdir dist
          die 
          echo "<h1>Hello BYU! Go cougs!</h1>" >> dist/index.html

      - name: Update pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/ #zips the html into a file
  deploy: # this gives me write permissions
    needs: build # you can call this whatever, "needs: build" just says the job "deploy" needs the job "build" to run first.
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
